version: "3"
services:
  postgres-database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./apps/postgres/prod:/var/lib/postgresql/data
  express-server-prod:
    build: ./apps/express
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file: .env
    ports: ["3000:3000"]
  express-server-two-prod:
    build: ./apps/express_two
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports: ["3001:3000"]
